### ISSUE TITLE
'collapseWhitespace' does not collapse non breaking space

### ISSUE THREAD

**Issue by goo32** [simplabs/qunit-dom#107]
### Issue

"\u00A0Foo\u00A0\u00A0Boo\u00A0" should collapse to "Foo Boo" but does not.

### Solution

In the function 'collapseWhitespace' update

".replace(/[\t\r\n]/g, ' ')"

to

".replace(/[\t\r\n\\u00A0]/g, ' ')"

**Comment by Turbo87** [comment]
No, it should not, since non breaking spaces are actually rendered and not collapsed by browsers

**Comment by goo32** [comment]
Ahhh, gotcha. I suppose in my case I should use a regex in the hasText assertion. Some background on how I got here:

My markup:

```
<ul class="breadcrumb">
  <li>
    <i class="an-icon">&nbsp;&nbsp;</i>Locations
  </li>
</ul>
```
My original assertion which was passing (Ember acceptance test)

```
assert.equal(find('ul.breadcrumb li:first-child').textContent.trim(), 'Locations');
```

Codemod refactoring to use qunit-dom and which fails

```
assert.dom(find('ul.breadcrumb li:first-child')).hasText('Locations');
```

My refactoring to make it pass

```
assert.dom(find('ul.breadcrumb li:first-child')).hasText(/Locations/);
```
