### ISSUE TITLE
Make it an npm package with 0 dependencies

### ISSUE THREAD

**Issue by izelnakri** [simplabs/qunit-dom#1135]
As I mentioned previously, this package shouldnt need to be an broccoli addon. Recently I made for example a qunit addon without dependencies that can be used for all qunit projects: https://www.npmjs.com/package/browser-inputs

Also it would be great if the dom assertions here could also run on server-side context. QUnitx can run a test file on node.js or browser interchangably so it would be great to be able to test written tests on server-side for SSR with no code changes.

I might create large PRs for these 2 changes separately if you are all ok with it.

**Comment by Turbo87** [comment]
> As I mentioned previously, this package shouldnt need to be an broccoli addon

It doesn't need to be, but it made the integration in Ember projects a lot easier for the users. Now that we have an explicitl initialization step it might not be as necessary, but I don't see any immediate need or reason to change what it currently working quite well.

> Also it would be great if the dom assertions here could also run on server-side context.

it does seem to work for fastboot (see https://embermap.github.io/ember-cli-fastboot-testing/docs/html), so I don't see any reason why it shouldn't work

> QUnitx can run a test file on node.js or browser interchangably

qunit-dom targets QUnit, not QUnitx 🤷‍♂️

**Comment by izelnakri** [comment]
Thanks for the link they seem to be doing a hacky setup to make it working here: https://github.com/embermap/ember-cli-fastboot-testing/blob/master/addon-test-support/index.js#L73 I find it hacky because it still requires running a browser instance, where it shouldnt need that bottleneck, all QUnit code can be run on node.js. Also there could be a better way/new API to fast query/assert them from the string without having to set it to another dom with `innerHTML`. 

I might work on this in the far future with my fork, intention is to make test files runnable on nodejs or browser with 0 code changes on the target test files, only a small generic and explicit setup API might be needed.
