### ISSUE TITLE
Is there a way to customize how assertion messages determine the name of an element?

### ISSUE THREAD

**Issue by NullVoxPopuli** [simplabs/qunit-dom#1169]
like, when a message says "expected X to exist" (paraphrasing, could be the has/contains text check or whatever), X could be (for a single element), a _really_ long name, if using tailwind. It'd be great to customize this so we could prioritize our data-test selectors (which unfortunately aren't `data-test=...`), over the `class`, and then fall back to the class if the test selector doesn't exist?

**Comment by Turbo87** [comment]
nope, there is currently no such functionality.

**Comment by NullVoxPopuli** [comment]
would you be open to a PR that adds some way to configure this? maybe in the `setup` method?

**Comment by Turbo87** [comment]
I think something like https://github.com/simplabs/qunit-dom/pull/905 will implement this as a side-effect
