### ISSUE TITLE
Provide a function to trim the innerText

### ISSUE THREAD

**Issue by siva-sundar** [simplabs/qunit-dom#141]

**Comment by Turbo87** [comment]
hasText trims by default already

**Comment by siva-sundar** [comment]
Sorry that I didn't leave a proper description earlier. Non breaking white spaces are not trimmed currently.

Consider the following scenario

```hbs
<div class="contact">
 {{svg-helper "contact"}}&nbsp;&nbsp;John
</div>
```

```javascript
assert.dom('.contact').hasText('Name'); // would fail
```

We could have a separate function to trim `&nbsp;` as well.

**Comment by Turbo87** [comment]
non-breaking spaces are rendered by the browser and not trimmed, which is why qunit-dom does the same thing
