### ISSUE TITLE
default assert.dom rootElement

### ISSUE THREAD

**Issue by Windvis** [simplabs/qunit-dom#1461]
The [docs](https://github.com/simplabs/qunit-dom/blob/master/API.md#assertdom) mention that `assert.dom` will use `document` as the rootElement if non is provided. In practice this doesn't seem to be the case.

Looking at the code it seems the default is to use [`#ember-testing` instead](https://github.com/simplabs/qunit-dom/blob/fca74b61c3bbaac65521c9a81e5b7b30350f734d/lib/qunit-dom-modules.ts#L16). Since qunit-dom isn't Ember specific I find that a strange default? I would have expected that the Ember blueprints would configure this rootElement for Ember users [by calling `setup` with the needed rootElement logic](https://github.com/ember-cli/ember-cli/blob/d3e6dd0f67a3eb3914561ffb595fcc3745d909b0/blueprints/app/files/tests/test-helper.js#L10) instead of "hardcoding" it in this package.

In any case, if it's kept like this I think the docs need to be updated? I was a bit confused why a certain element wasn't being found since the docs mentioned the default `document` behavior and it took me some source diving to find out why that was :smile:.

**Comment by Turbo87** [comment]
By default it should be using the `document` as the root element, unless you use it in an Ember app, then it should automatically switch to the test container. At least this is what the intention was, but something might have changed when we moved to the explicit setup call. 🤔

**Comment by Windvis** [comment]
Oh, that could be, I didn't take a detailed look but on first glance it seemed like it was setting that as the default if nothing else was passed in through the setup options object.

I am indeed using an Ember app. It's just that the docs don't mention that behavior which confused me since an element wasn't being found but it _was_ rendered, just not in Ember's `#ember-testing` element.

Passing in the rootElement fixes it of course.

**Comment by Turbo87** [comment]
yeah, that is somewhat intentional, because we don't want it to match on anything that is part of the QUnit user interface by default.
