### ISSUE TITLE
Make it possible to get the target element from the DOMAssertions instance

### ISSUE THREAD

**Issue by Windvis** [simplabs/qunit-dom#179]
That way you would not have to .querySelector the element yourself when you need it for other test helpers (for example ember-test-helpers).

```javascript
// ...
let buttonElement = this.element.querySelector('.some-button');
let domAssertion = assert.dom(buttonElement);
domAssertion.exists();

await click(buttonElement);
// ...
```

Could be changed to something like:
```javascript
// ...
let domAssertion = assert.dom('.some-button');
domAssertion.exists();

await click(domAssertion.element);
// ...
```

It would improve the DX a tiny bit, in my opinion 😁

Thoughts?

**Comment by Turbo87** [comment]
This might conflict with e.g. the `count` option on `exists()`

**Comment by Windvis** [comment]
O, yea, I didn't know that option existed. But to be fair, passing an HTMLElement to assert.dom also conflicts with that option, right?

The property suggestion was just an implementation detail. It could also just be a public method.

But fair enough if you don't think this is a good addition to the addon. Writing querySelectors is not the end of the world  😄.
