### ISSUE TITLE
Whitespace collapsing in `hasText` does not behave as expected

### ISSUE THREAD

**Issue by ajcolter** [simplabs/qunit-dom#186]
I have a translation string with HTML in it, and I wrote a test to verify that it renders, properly escaping the HTML.

My string looks like (simplified & redacted): 
`Something went wrong on our end. Please try again later or contact <a target="_blank" href="#support-team">our&nbsp;support&nbsp;team</a>.`

My test looks like: 
`assert.dom('[data-test-not-found-subtitle]').hasText('Something went wrong on our end. Please try again later or contact our support team.');`

In qunit I see this:
![screen shot 2018-11-09 at 6 03 38 pm](https://user-images.githubusercontent.com/1641344/48292773-dc9fb600-e449-11e8-9f5c-83c00a56fab5.png)

It seems like it isn't doing the right thing with the `&nbsp;`. I've tried copying the qunit result line into my test string, and it still doesn't recognize a match.

**Comment by ajcolter** [comment]
I see this previous issue, which looks related, but the expected behavior seems like it is different. https://github.com/simplabs/qunit-dom/issues/107

**Comment by Turbo87** [comment]
non-breaking spaces are not collapsed or replaced by qunit-dom, which is trying to behave just as rendering in the browser would. make sure to use non-breaking spaces in your expectation text and then it should work fine. unfortunately I don't know why copy-paste did not work for you, but I've used this in several projects and it's working exactly as intended.
