### ISSUE TITLE
Add `hasVisibleText()` assertion

### ISSUE THREAD

**Issue by gabrielcsapo** [simplabs/qunit-dom#196]
would you be interested in having a new function that allows you to filter out all the visible-hidden elements and just assert against the visibleText??

**Comment by Turbo87** [comment]
can you give a few examples of where this might be needed?

**Comment by gabrielcsapo** [comment]
@Turbo87 Testing text content that has visible-hidden content that is inlined with the visible text.

**Comment by gabrielcsapo** [comment]
Basically this would just filter out certain elements when getting the textContent, I guess this could be more generalized to just add a options argument to the hasText prototype.

```
hasText(selector, { ignoredSelectors="" })
```

**Comment by gabrielcsapo** [comment]
@Turbo87 thoughts on this?

**Comment by Turbo87** [comment]
this will most likely complicate the `hasText()` implementation a lot and I don't see the big benefits yet. is this related to responsive rendering where certain breakpoints show text and others don't?

**Comment by gabrielcsapo** [comment]
This is dealing with a11y visibility of text https://github.com/medialize/ally.js/blob/master/docs/tutorials/hiding-elements.md

**Comment by Turbo87** [comment]
@melsumner @nathanhammond any thoughts on this?

**Comment by nathanhammond** [comment]
There are so many ways that any particular piece of text can be "invisible" that it's not actually viable to determine this in code. At best this can identify certain failures, but it can't identify all of them.

I feel like assertions should be 100% correct, especially those provided by a library that is broadly consumed. The inability to do that means that I'm opposed to including this assertion.

**Comment by Turbo87** [comment]
@nathanhammond thanks, I guess that reflects my thoughts on this pretty well too

@gabrielcsapo due to the potential for false-positives/negatives we'll probably not add a `hasVisibleText()` assertion for now
