### ISSUE TITLE
New implementation of includesText fails when expected text contains line breaks

### ISSUE THREAD

**Issue by happycollision** [simplabs/qunit-dom#197]
After the change made to satisfy issue #104, you can no longer pass in text containing line breaks (or probably multiple spacing) as the expected text in `includesText`.

This is not a clear limitation in the documentation, and the resulting message in Ember is confusing:

<img width="572" alt="screen shot 2018-11-15 at 8 39 31 pm" src="https://user-images.githubusercontent.com/3663628/48597191-2264ee80-e922-11e8-860d-b995aa65fae1.png">

As you can see, it appears as though the test is failing because of the diff at the beginning of the string. If you are not distracted by the red highlight in the diff, you might notice that there is actually a line break discrepancy, too.

**Comment by Turbo87** [comment]
looks like this can be closed as #198 was merged and release a while ago
