### ISSUE TITLE
Asserting against one of multiple matches for a selector

### ISSUE THREAD

**Issue by ryanto** [simplabs/qunit-dom#240]
First, apologies if I'm misunderstanding or asking a question that doesn't make sense.

I'm currently writing an acceptance test for validation messages within a form. I want to test that multiple validation errors show up on the page when an incorrect form is submitted. The test looks something like this.

```js
test('I should get an error if I dont fill out email or password', async function(assert) {
  await visit('/');
  await fillIn('[data-test-id="email"]', '');
  await fillIn('[data-test-id="password"]', '');
  await click('[data-test-id="submit-login"]');

  assert.dom('[data-test-id="error-messages"]').exists();

  assert
    .dom('[data-test-id="error-message"]:nth-child(1)')
    .hasText("Please enter your email address");

  assert
    .dom('[data-test-id="error-message"]:nth-child(2)')
    .hasText("Please enter your password");
});
```

In order to get the specific error messages tested I used `nth-child(n)`. However, this feels like a brittle test because I don't really mind if the order of those messages changes. I wouldn't want a change in order to cause this test to fail.

So I guess that's what brought me here. Is there a best practice or way to write an assertion that says: "Any `[data-test-id="error-message"]` on the page has text `"Please enter your email address"`?

Thanks!

**Comment by Turbo87** [comment]
> So I guess that's what brought me here. Is there a best practice or way to write an assertion that says: "Any `[data-test-id="error-message"]` on the page has text `"Please enter your email address"`?

I can think of two ways of doing that:

### Solution 1

Each error has an id or uses the id of the corresponding input and you use that to select the correct error message element:

```js
assert
  .dom('[data-test-error="email"]')
  .hasText("Please enter your email address");
```

### Solution 2

In cases where a simple selector does not work, it sometimes makes sense to use regular QUnit assertions instead of qunit-dom:

```js
let errors = findAll('[data-test-id="error-message"]');
assert.ok(errors.any(el => el.textContent.includes('Please enter your email address')));
assert.ok(errors.any(el => el.textContent.includes('Please enter your password')));
```

**Comment by ryanto** [comment]
Gotcha! Thanks. I ended up with a solution similar to #2.
