### ISSUE TITLE
assert.dom(Element).exists() throws even if it exists

### ISSUE THREAD

**Issue by dwilhelmi** [simplabs/qunit-dom#245]
Even though officially the `dom` method accepts the `Element` type, when using it that way the `exists` method ends up throwing an error, even if the element exists. At root, this is because `exists` calls `findElements`, which is not currently set up to check for `this.target` being anything other than a string.

I have a PR inbound shortly to add support to `findElements` for having Element targets, but wanted to track it here also.

**Comment by Turbo87** [comment]
hmm, interesting, I was pretty sure I implemented it that way at first. Has this possibly changed lately?

**Comment by dwilhelmi** [comment]
Not sure - `findElement` currently supports Element targets, but `findElements` does not. As promised, I have pushed up a PR with a possible fix - https://github.com/simplabs/qunit-dom/pull/246

**Comment by patocallaghan** [comment]
I just came up against this issue using `assert.dom(element).isNotVisible()`, `findElements` doesn't allow using a HTMLElement

**Comment by step2yeung** [comment]
Bumping this... We see the error with `assert.dom(element).isVisible()`
@dwilhelmi will you have time to wrap up the PR? If not, would you care if I take it over?

**Comment by monovertex** [comment]
I also encountered this with `isNotVisible()`. Could the proposed PR be merged or is there any other work left to be done on it?

**Comment by scalvert** [comment]
Just to clarify, are folks encountering this issue using Typescript in their projects, and they're getting a type mismatch?

**Comment by patocallaghan** [comment]
@scalvert it's been a while since I've commented but we don't use TypeScript

**Comment by scalvert** [comment]
Let me take a peek again and see if there's anything outstanding we need on that PR.

**Comment by scalvert** [comment]
Sorry that everyone's been encountering this issue. I'm working on it now, and just adding a number of test cases to ensure that our fix is working.

**Comment by scalvert** [comment]
Ready to go! Just waiting for a merge/release. Thanks for your patience, everyone!
