### ISSUE TITLE
#doesNotExist() should not track previous state

### ISSUE THREAD

**Issue by izelnakri** [simplabs/qunit-dom#254]
example code:

```js
    assert.dom('.ember-modal-dialog').doesNotExist(); // passes

    // then click on a button for dialog

    assert.dom('.ember-modal-dialog').exists(); // passes

    // then close the dialog

    assert.dom('.ember-modal-dialog').doesNotExist(); // !!! THIS ONE FAILS!
```

It says Element .ember-modal-dialog exists once

**Comment by Turbo87** [comment]
I don't understand the issue. Apparently the `.ember-modal-dialog` element still exists at the point where you run the assertion.

**Comment by izelnakri** [comment]
The issue is qunit-dom tracks/caches previous existence when #doesNotExist() gets called. The test above fails where it should have passed. 

It could be that .ember-modal-dialog addon keeps the dom I'll check it shortly and get back to you however it is very unlikely and Im almost sure the issue here is the logic in the internal library implementation. The error doesnt say "Element .ember-modal-dialog exists" it says "Element .ember-modal-dialog exists once".

**Comment by Turbo87** [comment]
> The issue is qunit-dom tracks/caches previous existence when #doesNotExist() gets called

I don't think that's true. Why do you think that `qunit-dom` caches anything?

**Comment by izelnakri** [comment]
yes I've been missing the await there, my apologies 🤦‍♂️
