### ISSUE TITLE
Implement way to get element from assert.dom()

### ISSUE THREAD

**Issue by Frozenfire92** [simplabs/qunit-dom#306]
This would make it so we can use the cached variables from qunit-dom directly in ember-test-helpers

I propose adding a `.element` property to assert.dom() objects

Example:

```js
const button = assert.dom('button');

button.hasText('not clicked');

await click(button.element);

button.hasText('clicked!');
```

**Comment by Turbo87** [comment]
something like that is already possible:

```js
import { find } from '@ember/test-helpers';
```

```js
const button = find('button');

assert.dom(button).hasText('not clicked');

await click(button);

assert.dom(button).hasText('clicked!');
```

passing a selector to the `dom()` function is just a shortcut, the function also accepts regular DOM elements which you can find using the `find()` test helper.

**Comment by Frozenfire92** [comment]
awesome! this makes sense, might be worth being something explicitly added to the docs

**Comment by Frozenfire92** [comment]
Another option for anyone stumbling on this issue in the future:

you can use 
```js
const button = assert.dom('button');

await click(button.target);
```

this is useful for cases where the element isn't rendered yet (say via if/else block) as such you can't use find. `.target` will give you the original selector

**Comment by Turbo87** [comment]
`.target` is not public API though and shouldn't be used
