### ISSUE TITLE
Work with shadowroot

### ISSUE THREAD

**Issue by knownasilya** [simplabs/qunit-dom#315]
Currently this doesn't work:

```js
assert.dom(find('#internal').shadowRoot).hasText('template block text');
```

And doesn't look great. I can submit a PR to make it work, but would love something more ergonomic.

**Comment by Turbo87** [comment]
sorry, I've never worked with a `shadowRoot` before. how does this work? what does it do? and what do you think we can to to support it better?

**Comment by knownasilya** [comment]
So a ShadowRoot is a document fragment and hide's it's children from the outside, so if `#internal` has a shadowroot, it's content's are not directly accessible, but need to be queried via the `shadowRoot` attribute, which has the normal DOM querying APIs. So the easiest way to make this work would be to allow the target to be used directly if a ShadowRoot, i.e. changing https://github.com/simplabs/qunit-dom/blob/master/lib/assertions.ts#L960 to look like:

```js
    else if (this.target instanceof Element || this.target instanceof ShadowRoot) {
      return this.target;
    }
```

But a better API might look like:

```js
assert.shadow('#internal').hasText('template block text');
```

I'm not sure what edge cases there might be though.

**Comment by Turbo87** [comment]
```js
assert.dom('.something', find('#internal').shadowRoot).hasText('template block text');
```

does the that work? this should use `find('#internal').shadowRoot` as the context on which it will try to find `.something`

**Comment by knownasilya** [comment]
That does work, e.g. `assert.dom('.block', find('#internal').shadowRoot).hasText('template block text');` but this doesn't:  `assert.dom(undefined, find('#internal').shadowRoot).hasText('template block text');`, which probably should because the shadowRoot can have textContent.

**Comment by knownasilya** [comment]
The above syntax is fine to get things working, but once shadowdom is more widely adopted it will be in pretty much every test and the above isn't as clean as qunit-dom tries to be.

**Comment by Turbo87** [comment]
adding something like this IMHO seems out-of-scope for this plugin and would make the implementation somewhat more complicated, which I would like to avoid, so I'll go ahead and close this. if `shadowRoot` at some point becomes more mainstream in Ember projects we can revisit this :)

**Comment by amark-axcient** [comment]
Any chance we could re-open this? It's pretty hard to test anything built with the Web Component standard when `shadowRoot` returns `null`.

**Comment by gordon-addepar** [comment]
> adding something like this IMHO seems out-of-scope for this plugin and would make the implementation somewhat more complicated, which I would like to avoid, so I'll go ahead and close this. if `shadowRoot` at some point becomes more mainstream in Ember projects we can revisit this :)

FWIW Addepar is using web components now.
