### ISSUE TITLE
Allow asserting against the root element (e.g. without `target`).

### ISSUE THREAD

**Issue by rwjblue** [simplabs/qunit-dom#34]
The following should be possible:

```js
test('element has class', function(assert) {
  assert.dom().hasClass('data-foo');
});
```

However, the following error is thrown:

```
TypeError: Unexpected Parameter: undefined
```

The current work around (in Ember's `moduleForComponent` parlance) is:

```js
test('element has class', function(assert) {
  this.render(hbs`{{some-thing}}`);

  assert.dom(this._element).hasClass('foo');
});
```

**Comment by Turbo87** [comment]
I am a little worried about this out of several reasons:

- it looks like glimmer just moved away from `this.element` towards `this.bounds.first/last`

- it creates a somewhat more strong coupling between `qunit-dom` and it being used in Ember, while it is designed to be framework-agnostic

- it is relatively easy to pass in `this._element` (or `this.element` for the new testing API)

- it is rather uncommon to run assertions on the container element, you usually want to assert on the component element that you rendered so this seems like an artificial example

**Comment by rwjblue** [comment]
1) seems unrelated, the `this.element` in the test harness would still be _something_
2) It does (in general) make sense to be able to assert on the rootElement if that rootElement is actually part of the thing being tested.  This does not seem related to Ember to me. 🤔
3) Totally agreed! And I think that is a perfectly fine resolution here...
4) It depends on how a host testing system uses the root element.  I'd generally agree with you that it would be better for most involved to use a `rootElement` that _contains_ the actual contents you are asserting against, rather than asserting against the `rootElement` itself.

Thanks for chatting this through! I don't feel super strongly, and mostly just wanted to raise the idea to see what y'all thought.  Please close if you'd rather stick to the 3rd bullet above (but we should probably document that as an example in API.md)...
