### ISSUE TITLE
Support passing in dom elements as well as strings

### ISSUE THREAD

**Issue by NLincoln** [simplabs/qunit-dom#35]
My use case: interop with `ember-native-dom-helpers` which returns dom elements. 

That way I can write things like:

```js
import { find } from 'ember-native-dom-helpers';

test('it exists', async function(assert) {
  assert.dom(find('h1')).hasClass('bar');
});
```

**Comment by Turbo87** [comment]
You can already do that, but there is no reason to do it in this case because dom() already does pretty much the same thing as find()

**Comment by NLincoln** [comment]
My apologies, it wasn't obvious from looking at the docs + code.
