### ISSUE TITLE
Add `hasNoText()` assertion

### ISSUE THREAD

**Issue by Turbo87** [simplabs/qunit-dom#356]
this would essentially be an alias for `hasText('')` with custom assertions messages

**Comment by timo-lindemann-victors** [comment]
As a side note, for this use case one can use `matchesSelector()` and check for the additional pseudo class `:empty`. 

Elements that match `selector:empty` have no child nodes (text or otherwise), which is more specific than "no text", but it is what I, personally, typically want to check.
