### ISSUE TITLE
add support for multiple elements

### ISSUE THREAD

**Issue by kellyselden** [simplabs/qunit-dom#37]
I extracted https://github.com/kellyselden/ember-text-test-helper from an app without knowing `hasText` does whitespace collapsing. I would like to ditch my addon, but to reach feature parity, this project would need to support selectors that match multiple elements and "combine", as well as `assert.dom(document.querySelectorAll('div'))`.

I think @Turbo87 is open to it, but every assertion will need to be updated. For instance `hasAttribute` will probably turn into a "all have attribute".

**Comment by marcoow** [comment]
Just my 2 cents but this sounds like quite some magic that doesn't add a ton of value? I guess in the example you mention above you could select the parent element instead and assert on the `text` of that?

The case with `hasAttribute` seems to indicate some confusion already - how would you make that clear via the API that the meaning for a list of node is _"all nodes have the attribute"_ - why not _"one node has the attribute"_?

**Comment by kellyselden** [comment]
Use cases:

```js
let rows = findAll('[data-test-row]');

// do a bunch of stuff/assertions on these rows

assert.dom(rows).hasText('1 2 3');
```

and

```hbs
<div>
  {{#each rows as |row|}}
    <div>
      <span data-test-title>{{row.title}}</span>
      <span data-test-body>{{row.body}}</span> // assert.dom('[data-test-body]').hasText('1 2 3');
    </div>
  {{/each}}
</div>
```

They aren't very common use cases, but that's what I was thinking when I did https://github.com/kellyselden/ember-text-test-helper/blob/master/addon-test-support/text.js#L6-L8.

**Comment by marcoow** [comment]
I think that mixes access to the DOM and its properties with convenience methods for joining properties of a collection of things though. In the end the above is the same as

```js
let rows = findAll('[data-test-row]');

// do a bunch of stuff/assertions on these rows

assert.equals(rows.map(r => r.text).join(' '), '1 2 3'));
```

**Comment by kellyselden** [comment]
It's a bit more code than that:

```js
assert.equals(Array.from(rows, r => r.textContent).join(' ').trim().replace(/[\n ]+/g, ' '), '1 2 3'));
```

**Comment by marcoow** [comment]
Yeah sure, my point was more that this might be unrelated convenience functionality for some very specific use cases and encapsulating all of the logic of

```js
assert.equals(Array.from(rows, r => r.textContent).join(' ').trim().replace(/[\n ]+/g, ' '), '1 2 3'));
```

in

```js
assert.dom(rows).hasText('1 2 3');
```

seems like a bit too much magic for my taste.

**Comment by Turbo87** [comment]
@kellyselden we could also just export our whitespace collapsing function as public API. Would that help?

**Comment by Turbo87** [comment]
this issue has gone somewhat stale and I haven't been able to come up with a convincing API yet so I'm closing the issue for now.

**Comment by runspired** [comment]
@Turbo87 how about either:

```js
assert.dom("selector")
  .exists({ count: 2 })
  .at(0) // get the first index and continue chaining from there
  .hasAttr("thing");
  
assert.dom("selector")
  .exists({ count: 2 })
  .each((dom, index) => {
     dom.hasAttr("thing"); // continue asserting with each of the individual things
  })
```

**Comment by runspired** [comment]
@Turbo87 to be clear I'm not proposing accessors, though that would be a powerful eject button I wouldn't *mind* having, I'm proposing the ability for it to return new instances of `assert.dom` on an individual child of the original selector. This would *massively* cleanup a lot of dom assertions I've seen, and also naturally be bounded to a single level of decomposition since it's not possible to further select within a selected element <3
