### ISSUE TITLE
Find element in context of another element

### ISSUE THREAD

**Issue by amk221** [simplabs/qunit-dom#374]
I often find myself wanting to use qunit-dom's api to query for elements within the context of another element. Like this:

```javascript
const myParentElement = find('.my-parent');

await click(find(myParentElement, '.toggle-me'));

assert.dom(aParentElement, '.my-child').exists();
```

I raised a related 'wishlist' issue here: https://github.com/emberjs/ember-test-helpers/issues/658

**Comment by Turbo87** [comment]
@amk221 I'm not sure I understand correctly but `assert.dom('.my-child', aParentElement).exists();` should already work

**Comment by amk221** [comment]
oh really? how did I not know that.
