### ISSUE TITLE
Add isDisabled() assertion

### ISSUE THREAD

**Issue by livet01** [simplabs/qunit-dom#38]
Adding `checked` and `disabled` states to be able to assert them easily:
```javascript
assert.ok(find('input[type="checkbox"]').checked);
assert.dom('input[type="checkbox"]').isChecked();

assert.ok(find('input[type="checkbox"]').disabled); 
assert.dom('input[type="checkbox"]').isDisabled();
```

Also what about `readonly` or `required`?

**Comment by Turbo87** [comment]
I guess we should probably have a generic `hasProperty()` assertion roughly similar to `hasAttribute()`, but having those shortcut assertions for the most common properties should also be useful.
