### ISSUE TITLE
assert.dom('select.foo').selection.hasText()

### ISSUE THREAD

**Issue by Turbo87** [simplabs/qunit-dom#41]
It would be awesome if there was an easier way to run assertions on the selected `<option>` of a `<select>` element. Proposal:

```js
assert.dom('select.foo').selection.hasText('Foo!');
```

instead of

```js
assert.dom([...this.element.querySelector('select.foo').querySelectorAll('option')].find(it => it.selected)).hasText('Foo!');
```

**Comment by marcoow** [comment]
Do `assert.dom('select.foo option:checked')` or `assert.dom('select.foo option:selected')` not work?

**Comment by Turbo87** [comment]
```
Failed to execute 'querySelectorAll' on 'Document': '#ember-testing select.foo option:selected' is not a valid selector.
```

**Comment by Turbo87** [comment]
`:checked` actually seems to work though... interesting!

seems quite unintuitive though 🤔
