### ISSUE TITLE
Add a SCOPE option into .dom()

### ISSUE THREAD

**Issue by cepm-nate** [simplabs/qunit-dom#42]
I run tests by dropping an iFrame of the target into my testrunner.html file. Then I do

  a = document.getElementById('idOfiFrame').contentWindow;

This allows me to view the visual state of the page as it's being tested. I test all target functions via a.targetFunctionName.

Your plugin looks great, but I can't figure out how to make the .dom() test things within (a), instead of the testrunner.html window.

Any tips?

**Comment by Turbo87** [comment]
@cepm-nate the `dom()` method accepts a second argument that can be used as the scope element:

```
let a = document.getElementById('idOfiFrame').contentWindow;
assert.dom('.foo', a).hasText('bar');
```

as an alternative you can also define a `rootElement` property on `QUnit.assert.dom` like we do for the Ember.js integration: https://github.com/simplabs/qunit-dom/blob/f36a86abc068c8efe77fda94612392f4366e5305/vendor/overwrite-qunit-dom-root-element.js#L1-L7

**Comment by cepm-nate** [comment]
Powerful! Thanks @Turbo87 .

**Comment by cepm-nate** [comment]
Updated response above ^^

**Comment by Turbo87** [comment]
have you checked that `document.querySelector('#mm')` actually returns something useful?

**Comment by cepm-nate** [comment]
It returns the iframe (in google chrome console).

**Comment by cepm-nate** [comment]
This works:
    Object.defineProperty(QUnit.assert.dom, 'rootElement', { 
	   get: function() { 
		 return document.querySelector('#mm').contentWindow.document; 
	   }, 
	   enumerable: true, 
	   configurable: true, 
	 }); 

I had to add .contentWindow.document, so that subsequent calls to 'querySelector' would correctly query the document object.

Thanks for your patience. I'm posting this just in case someone else runs across it as well.
