### ISSUE TITLE
.hasClass() error message is confusing when it fails

### ISSUE THREAD

**Issue by cepm-nate** [simplabs/qunit-dom#43]
Say you have an element like `<div id="fun" class="thing1 thing2 thing3">`, and your testing code is written like `assert.dom('#fun').hasClass('thing1')`.

IF it does not find a class, it fails with "Expected: thing1", "Result: thing8 thing2 thing3".

... I guess this is not a very important issue.

**Comment by Turbo87** [comment]
@cepm-nate the assertion message shows you what you expected to find and what classes are really on the element. I don't think there is much we can do to make this less confusing. If we removed the "Result: ..." part the assertion would be much less helpful if it failed.
