### ISSUE TITLE
Able to use Xpath syntax?

### ISSUE THREAD

**Issue by Mifrill** [simplabs/qunit-dom#442]
The browsers natively support the `Xpath` syntax, I think that would be nice to use here this syntax too.
Can you please consider this suggestion?
Thank you

**Comment by Turbo87** [comment]
we use `querySelector()` under the hood. if that supports XPath then qunit-dom supports it too, if not then I don't see how we would implement that.

**Comment by Mifrill** [comment]
@Turbo87 what about use this package:
https://www.npmjs.com/package/xpath-to-css
we can change the target value here:
https://github.com/simplabs/qunit-dom/blob/10bda5563d5573793b5d40e16b0dec9485310070/lib/assertions.ts#L949-L960
to use it with the param: 'xpath' for example:
`assert.dom('//XPATH', xpath: true)`

**Comment by Turbo87** [comment]
you said that "browsers natively support the Xpath syntax", but why do we need an extra npm package to support it then?

another question: why do we need XPath syntax at all? are CSS selectors and/or ember-test-selectors not sufficient?

**Comment by Mifrill** [comment]
1) because of `assert.dom("//a")` is raised an error
2) because of it's better working with complex path's, example: `//*[@class='item-details' or @id='standard-specs']//li`

**Comment by Turbo87** [comment]
I don't think we will build this into qunit-dom itself, but it should be easy to use on top of it:
```js
import xpath from 'xpath-to-css';

assert.dom(xpath('//a')).exists();
```
