### ISSUE TITLE
Typescript does not find type definitions for qunit-dom

### ISSUE THREAD

**Issue by LucasHill** [simplabs/qunit-dom#443]
I noticed that without adding the '@types/qunit-dom' package that I would get no recognition of types for qunit-dom on the qunit assert object. Those type definitions were out of date, so I went and updated them [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37377). It was brought to my attention that this project is actually written natively in Typescript. All the same, type definitions are not coming through to the consumer of the library. I tried this on a brand new ember project and its still the same. Thoughts? Thank you.

**Comment by Turbo87** [comment]
did you see https://github.com/simplabs/qunit-dom#typescript?

**Comment by LucasHill** [comment]
No I didn't, whoops. Thank you.
