### ISSUE TITLE
rootElement in assert.dom()

### ISSUE THREAD

**Issue by MichalBryxi** [simplabs/qunit-dom#45]
When I'm testing multiple elements in one particular area I need to write something like:

```js
let rootElement = document.querySelector(".super .long .selector .that .i .dont .want .to .repeat");

assert.dom('.foo', rootElement).hasText('foo');
assert.dom('.bar', rootElement).hasText('bar');
assert.dom('.baz', rootElement).hasText('baz');
...
```

- Because `rootElement` can be only `HTMLElement`, I can't use simple CSS selector string. Not really a problem, since that would come with performance penalty anyway.
- I'm wondering whether there is different, more "standard" way to write this? Namely asking about `document.querySelector` which feels really "bare" to use.

**Comment by Turbo87** [comment]
@MichalBryxi this looks like a good solution to me. I don't think it can or should be written much differently.
