### ISSUE TITLE
Regex support for hasClass / doesNotHaveClass

### ISSUE THREAD

**Issue by timiyay** [simplabs/qunit-dom#450]
I recently needed to use a regex to match against a CSS class, which `hasClass` and `doesNotHaveClass` don't currently support.

Would this feature be considered, if I opened a PR?

The context is:

- I'm using namespaced CSS modules, which prepend a unique string to CSS classes, like `d66d3pf_my-component_is-great`
- I don't know this `d66d3pf` prefix within my tests
- I would like to check that the CSS class is present / absent, while ignoring the prefix

Here's what I'm doing right now, within an EmberJS component rendering test:

```js
const cssClasses = this.element.classList.value
assert.ok(cssClasses.match(/my-component_is-great/))
```

**Comment by Turbo87** [comment]
yeah, that seems reasonable to me. I assume you are using ember-css-modules?

**Comment by timiyay** [comment]
I'm using https://github.com/ebryn/ember-component-css, though the principle is the same.

I'd originally thought I could call `component.styleNamespace` in my rendering test and look it up, but couldn't find any obvious way to do that, and the docs speak nothing of it. I got the vibe that directly calling component methods within rendering tests isn't encouraged.

**Comment by timiyay** [comment]
@Turbo87 I've implemented regex support for `hasClass` and `doesNotHaveClass` in https://github.com/simplabs/qunit-dom/pull/451. Please let me know what you think, whenever you have spare time to take a peek.

Thanks in advance 🙏
