### ISSUE TITLE
Add DOMAssertions#dom

### ISSUE THREAD

**Issue by garjust** [simplabs/qunit-dom#461]
Several times while authoring tests I've found myself wanting to chain `dom()` functions. What do you think about making `dom` a function available on `DOMAssertions` which does ` querySelector` on `targetElement` returning a new `DOMAssertions` object?

Example scenario:

```
const parentSelector = '#foo`
const childSelector = '#boo'

// with a chainable dom() function
assert.dom(parentSelector).exists()
assert.dom(parentSelector).dom(childSelector).exists()

// without
assert.dom(parentSelector).exists()
assert.dom(`${parentSelector} ${childSelector}`).exists()
```

**Comment by Turbo87** [comment]
I'm not a big fan of this, since we already have a roughly similar feature on the `dom()` function itself.

```js
const parentSelector = '#foo`
const childSelector = '#boo'

const parent = find(parentSelector)

assert.dom(parent).exists()
assert.dom(childSelector, parent).exists()
```

and if you must use selectors then using ``dom(`${parentSelector} ${childSelector}`)`` doesn't seem that bad to me.

**Comment by scalvert** [comment]
I also agree with @Turbo87. It seems somewhat disorienting to see separate selectors chained together. Is this expected to operate in a jQuery-esque fashion, where it has a wrapped set of DOM elements?

Additionally, the beauty of pure assertions is that they assert on one thing, so if they fail it's clear what failed. In this example:

```
assert.dom(parentSelector).dom(childSelector).exists()
```

what if `parentSelector` exists but `childSelector` doesn't? While we can adapt the message to accommodate this, I feel like it's nice just to write specific, verbose assertions.

I'm open to counter arguments.
