### ISSUE TITLE
string.replace is not a function

### ISSUE THREAD

**Issue by MichalBryxi** [simplabs/qunit-dom#47]
Following code:

```js
  assert.dom('.some-existing-element').hasText(1234);
```

Produces following exception:

```
TypeError: string.replace is not a function
    at collapseWhitespace (http://localhost:7357/assets/test-support.js:7820:17)
    at DOMAssertions.hasText (http://localhost:7357/assets/test-support.js:8124:20)
    at Object._callee$ (http://localhost:7357/assets/tests.js:244:52)
    at tryCatch (http://localhost:7357/assets/vendor.js:381:40)
    at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:655:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:7357/assets/vendor.js:414:21)
    at step (http://localhost:7357/assets/tests.js:194:32)
    at http://localhost:7357/assets/tests.js:205:15
    at <anonymous>
```

I believe it goes down to [this line](https://github.com/simplabs/qunit-dom/blob/master/lib/helpers/collapse-whitespace.js#L3). And the fact that I'm passing down number instead of string.

I know that `hasText()`'s API is defined as: `expected (string | RegExp)`, but the library should at least warn about unsupported parameter and not blow up. Preferably though, I'd like to see automatic conversion from number to string #justWorks™

**Comment by Turbo87** [comment]
Thanks for reporting this. I'm not sure if we should convert automatically. It seems error prone to me 🤔

**Comment by MichalBryxi** [comment]
Another observation: `hasValue` behaves the same:

```
assert.dom('.foo-bar').hasValue(1234);
```

**Comment by MichalBryxi** [comment]
@Turbo87 Yeah, I also sense that trying to be smarter than developers might lead to troubles. Like `2.0` rendering as `2` or `2.0` or similar stuff. I'm really just asking here for sensible message :)

**Comment by MartinMalinda** [comment]
if `assert.equal(find('.some-el').textContent, 1234);` passes, `assert.dom('.some-el').hasText(1234);` should too IMO

**Comment by Turbo87** [comment]
@MartinMalinda I disagree. `textContent` is defined to be a `DOMString` (see https://www.w3.org/TR/2004/REC-DOM-Level-3-Core-20040407/core.html#Node3-textContent) and as such can not be equal to a number. `assert.equal()` only works because it uses `==` internally instead of `===`, which would be `assert.strictEqual()`.

**Comment by MartinMalinda** [comment]
>only works because it uses == internally instead of ===

yes, that was my point :)
