### ISSUE TITLE
Add hasTag() assertion

### ISSUE THREAD

**Issue by jelhan** [simplabs/qunit-dom#493]
If I didn't missed something, qunit-dom does not provide yet any assertion for the `tagName` of an element. Something like this:

```js
assert.equal(document.querySelector('[data-test-foo']).tagName, 'P', 'is a paragraph');
```

I'm not opinionated on the concrete naming but something like this would be a nice addition to the API:

```js
assert.dom('[data-test-foo']).hasTag('p');
```

As shown in the example I would recommend that the check is done case-insensitive.

**Comment by Turbo87** [comment]
indeed, that might be a good addition. especially the case insensitivity would be good. are you interested in working on a PR for this?

**Comment by jelhan** [comment]
> are you interested in working on a PR for this?

I'm always interested but having the feeling that I'm currently trying to work on to many repos at the same time. Need to focus to actually finish some stuff. So I'm not sad if someone else is picking that one up. :smile:

**Comment by scalvert** [comment]
I gotchu, @jelhan.

**Comment by esantelises** [comment]
@Turbo87 do we have a date when this feature going be release ?

**Comment by Turbo87** [comment]
@esantelises sorry for the delay. https://github.com/simplabs/qunit-dom/releases/tag/v0.9.1 is out now.

**Comment by esantelises** [comment]
thank you @Turbo87
