### ISSUE TITLE
isVisible() / isNotVisible() throw error with HTMLElement as parameter

### ISSUE THREAD

**Issue by woprandi** [simplabs/qunit-dom#508]
Hi,

`isVisible()` and` isNotVisible() `throw an error if the parameter is a DOM node

```
// WORKS
assert.dom(".foo").isVisible() 

// THROW ERROR
assert.dom(document.querySelector(".foo")).isVisible()
```

other assertions like `hasText` / `hasValue` accept HTMLElement as parameter.

**Comment by scalvert** [comment]
Duplicate of #245.
