### ISSUE TITLE
Add isChecked() assertion 

### ISSUE THREAD

**Issue by martndemus** [simplabs/qunit-dom#51]
That would be great!

**Comment by Turbo87** [comment]
I guess this is a duplicate of https://github.com/simplabs/qunit-dom/issues/38, but more focused on a single assertion, so I'll keep this open. PRs obviously welcome 😉

**Comment by martndemus** [comment]
🤦‍♀️ oops, did not check the issues well enough. Sorry about that!

**Comment by Turbo87** [comment]
no worries, the other issue doesn't have a particularly expressive title 😉
