### ISSUE TITLE
Time to release 1.x.x version?

### ISSUE THREAD

**Issue by ondrejsevcik** [simplabs/qunit-dom#541]
Hi, 

first of all, thanks for the awesome package, I really enjoy using it. 

I wanted to ask if it's not a time to release this as a v1.x.x. The 0.x.x. versions are for an initial development, but this library seems very stable to me. 

Just a suggestion, feel free to close this issue.

Thanks,
Ondrej

**Comment by Turbo87** [comment]
yeah, you're right, it's mostly stable. there are a few details to still figure out but I don't think it should block us from releasing this as a stable version. I would wait for the Node 8 EOL though to avoid having to release a v2 just a few weeks after the v1.

**Comment by Turbo87** [comment]
done
