### ISSUE TITLE
Add hasProperty() assertion

### ISSUE THREAD

**Issue by Turbo87** [simplabs/qunit-dom#55]
This assertion should work roughly similar to `hasAttribute()` and can then be used to check for properties that don't have dedicated assertions (like `hasValue()`).

**Comment by PBeier** [comment]
I would like to work on this

**Comment by Turbo87** [comment]
@PBeier make sure to have a look at #46. Most of it is already implemented in that PR, but I suggested a small API change there that is not implemented yet.
