### ISSUE TITLE
`hasStyle` / `doesNotHaveStyle`: empty `expected` should throw

### ISSUE THREAD

**Issue by buschtoens** [simplabs/qunit-dom#555]
I've encountered usages like this in the wild:

```js
test('button can toggle color', function(assert) {
  await render(hbs`<ToggleColorButton class=".btn" @on="#00FF00" />`);
  
  // toggle on the button
  await click('.btn');

  // button has `on` color
  assert.dom('btn').hasStyle({ backgroundColor: '#00FF00' });

  // toggle the button off again
  await click('.btn');

  // `on` color has been removed
  assert.dom('btn').hasStyle({});
});
```

The last LOC incorrectly assumes, that `hasStyle({})` asserts that all "custom" styles have been removed. In reality `hasStyle({})` does not assert anything:

https://github.com/simplabs/qunit-dom/blob/2a73e56344829a6f1fd3b28cd5df6b4ee1d00b75/lib/assertions.ts#L583-L586

I would suggest to throw an error or fail the assertion, when an empty object is passed to `hasStyle`, as this can never be a valid assertion and is most likely a mistake of the author of the test.

**Comment by Turbo87** [comment]
agreed, seems reasonable to show a helpful error message in those cases 👍
