### ISSUE TITLE
Add isRequired() and isNotRequired() assertions

### ISSUE THREAD

**Issue by Turbo87** [simplabs/qunit-dom#56]
This assertion should check if the `required` property of e.g. an `<input>` element is `true` or not.

#### Example: 
```js
assert.dom('.username-field').isRequired();
assert.dom('.coupon-code').isNotRequired();
```

**Comment by scalvert** [comment]
Also, the attribute being present also represents `true`, so the assertion should take that into consideration too.

**Comment by billybonks** [comment]
@Turbo87 guess you can mark this as complete
