### ISSUE TITLE
hasProperty assertion doesn't seem to allow checking a nested property

### ISSUE THREAD

**Issue by ijlee2** [simplabs/qunit-dom#616]
When I tried out `hasProperty` on QUnit DOM v1.0, I couldn't figure out how I might access a nested property in a DOM object.

Example 1.

```handlebars
<div data-test-message style="font-weight: 700;">
    Hello world!
</div>
```
```javascript
assert.dom('[data-test-message]')
  .hasProperty('style.fontWeight', '700');  // actual value = undefined
```

Example 2.
```handlebars
{{!--
  A line element in an svg represents an edge in a graph
  and keeps track of the IDs of connecting vertices
--}}
<line
  data-test-edge
  data-vertex-start="0"
  data-vertex-end="1"
  ...
/>
```
```javascript
assert.dom('[data-test-edge]')
  .hasProperty('dataset.vertexStart', '0')   // actual value = undefined
  .hasProperty('dataset.vertexEnd'  , '1');  // actual value = undefined
```

I was wondering if it's possible to update https://github.com/simplabs/qunit-dom/blob/master/lib/assertions.ts#L464 to account for nesting?

**Comment by Turbo87** [comment]
you can't, but you can use the `hasStyle()` assertion for that.

**Comment by ijlee2** [comment]
> you can't, but you can use the `hasStyle()` assertion for that.

Yep, definitely. What do you think about the 2nd example? I wasn't sure if there's value to checking custom data values in a test.

**Comment by Turbo87** [comment]
yep, exactly, those should use `hasAttribute()` instead

**Comment by ijlee2** [comment]
Cool, thanks for sharing your feedback. I'll close this issue.
