### ISSUE TITLE
Add `isEnabled()` alias for `isNotDisabled()`

### ISSUE THREAD

**Issue by Turbo87** [simplabs/qunit-dom#647]
because...

**Comment by mum-never-proud** [comment]
Hey, I am gonna take this if it's not already been taken

```javascript
let actual =
    element.disabled === false
      ? `Element ${this.targetDescription} is not disabled`
      : `Element ${this.targetDescription} is disabled`;

  let expected = inverted
    ? `Element ${this.targetDescription} is not disabled`
    : `Element ${this.targetDescription} is disabled`;
```

I don't think even when using `isEnabled` we should use the same message `is not disabled`

having a condition check? like providing `aliased` in `options` and change the message `is enabled` || `is not disabled` based on params passed?

i don't think there will be any further aliases for this

@Turbo87

**Comment by Turbo87** [comment]
@mum-never-proud thanks for looking into this. I think using the same assertion message as for `isNotDisabled()` is fine. we only need a simple method name alias here. there are quite a few other aliases in qunit-dom already that use similar patterns.

**Comment by mum-never-proud** [comment]
sure will raise in sometime
