### ISSUE TITLE
Add `hasAria()` assertion

### ISSUE THREAD

**Issue by Turbo87** [simplabs/qunit-dom#652]
This could act as a shortcut for `hasAttribute()`:

```js
hasAria(name, value, message) {
  hasAttribute(`aria-${name}`, value, message);
}
```

@melsumner thoughts?

**Comment by MelSumner** [comment]
I like it because it seems like it will help bring this more into the developer's conscious stream while they're writing tests. 👍

**Comment by scalvert** [comment]
I think this may have been what I was getting at with https://github.com/simplabs/qunit-dom/pull/99#issuecomment-539138380. 

👍
