### ISSUE TITLE
isScrollable Assertion

### ISSUE THREAD

**Issue by mum-never-proud** [simplabs/qunit-dom#661]
simple assertion to check the given element is scrollable by comparing elements 

`clientHeight` and `scrollHeight`

I can raise PR if needed

thoughts?

**Comment by Turbo87** [comment]
this doesn't seem like a very common thing to test for and usually depends on the browser window size, so I'm a little hesitant to adding an assertion for such a specialized use-case.

@scalvert thoughts?

**Comment by scalvert** [comment]
That’s my thinking too. Tests like this are notoriously hard to stabilize, and baking this into an assertion may not be ideal.

**Comment by mum-never-proud** [comment]
closing
