### ISSUE TITLE
Add form validation assertions

### ISSUE THREAD

**Issue by luxferresum** [simplabs/qunit-dom#701]
It would be nice to be able to do

```
assert.dom('.my-input').isValid();
assert.dom('.my-input').isNoValid();
```

We could simply run `.checkValidity()` on the element.
Is it an option to add this?
Would a PR with that get accepted?

**Comment by scalvert** [comment]
Hey @luxferresum,

Interesting idea. I'd be OK with this addition. @Turbo87?

**Comment by Turbo87** [comment]
sounds like a reasonable proposal to me. I've never had the need for such an assertion, but I'm open to trying it out 👍

**Comment by patsy-issa** [comment]
Added but not release yet, closing the issue :)
