### ISSUE TITLE
Consider allowing `null` and `undefined` for doesNotExist

### ISSUE THREAD

**Issue by amk221** [simplabs/qunit-dom#724]
Consider the following

```javascript
assert.dom(findMatching('button', 'Suspend')).doesNotExist('cannot suspend user')
```

When there is no button (`undefined`) this is output:

```
Expected: "Element div#ember-testing.ember-application[data-ol-has-click-handler] does not exist"
Result: "Element div#ember-testing.ember-application[data-ol-has-click-handler] exists once"
```

It also means I have to bypass qunit dom, like this:

```javascript
assert.dom(findMatching('button', 'Restore')).exists('can restore user')
assert.ok(!findMatching('button', 'Suspend'), 'cannot suspend user')
```

...I see there are [tests](https://github.com/simplabs/qunit-dom/blob/master/lib/__tests__/does-not-exist.ts#L79) for this exact scenario, but I wonder if you would consider changing it?

**Comment by patsy-issa** [comment]
Could you share your `findMatching` method it seems it already is bypassing `qunit-dom`

**Comment by amk221** [comment]
Yes, you're right it does seem that way. It came about due to a migration from the old days when we were using jQuery `:contains`.

There doesn't seem to be a way to do it with qunit-dom (unless I'm missing something).


```javascript
import { findAll } from '@ember/test-helpers';

export function findAllMatching(selector, pattern) {
  return findAll(selector).filter(element => element.textContent.match(pattern));
}

export function findMatching() {
  return findAllMatching(...arguments)[0];
}
```

If I could do it without my test-helper, then all the better!

That said, I still find it confusing that `assert.dom(undefined)` defaults to the application element... to me `undefined` means something doesn't exist.

Thanks for your response

**Comment by patsy-issa** [comment]
This is intentional to allow for `assert.dom().containsText('foo');` see https://github.com/simplabs/qunit-dom/issues/57

**Comment by patsy-issa** [comment]
@amk221 would using [ember-test-selectors](https://github.com/simplabs/ember-test-selectors) help refactor away from using `:contains`?

**Comment by amk221** [comment]
Thanks. That's not something I want to use. No problem if you want to close the issue

**Comment by amk221** [comment]
Just want to re-start the conversation. 

I still think it's pretty bad that you can write code like this:

```javascript
dom(reallyScaryDeleteButton()).doesNotExist('should not be able to delete');
```

...and for it to pass.

**Comment by patsy-issa** [comment]
I agree that a potential false positive outweighs a convenience method, we could deprecate this usage and offer a code mod to migrate away from `assert.dom().containsText('foo');` to `assert.dom(document).containsText('foo');` @Turbo87 @mansona thoughts?

**Comment by Turbo87** [comment]
> from `assert.dom().containsText('foo');` to `assert.dom(document).containsText('foo');`

those are not equivalent, and since we have access to `arguments.length` there is no need to deprecate `assert.dom()`.

> `assert.dom(this.reallyScaryDeleteButton()).exists('can delete');`

why not use `assert.ok(this.reallyScaryDeleteButton());` instead if you're side-stepping half of qunit-dom anyway?

**Comment by patsy-issa** [comment]
Hmm could get a PR going this week to address non-existent elements when passed in as arguments, shall we move the discussion to another issue, i think addressing what we will be doing with isVisible is related.

**Comment by amk221** [comment]
@Turbo87 I am. Point was just that it's easy to make a mistake.

**Comment by patsy-issa** [comment]
Opened https://github.com/simplabs/qunit-dom/issues/736 to track this potential false positive.

Thank you for reporting it 👍
