### ISSUE TITLE
Add `isNotDisabled` assertion

### ISSUE THREAD

**Issue by Turbo87** [simplabs/qunit-dom#73]
https://github.com/simplabs/qunit-dom/pull/62 added a `isDisabled()` assertion, but the reverse (`isNotDisabled()`) is still missing.

/cc @rtablada

**Comment by jackbeegan** [comment]
@Turbo87 @rtablada 
Hey, any chance I could look at taking this on? I'm a first time contributor.

**Comment by Turbo87** [comment]
@jackbeegan sure, let me know if you need any assistance :)

**Comment by Turbo87** [comment]
resolved by #74, thanks @jackbeegan! :)
