### ISSUE TITLE
Account for null element passed in

### ISSUE THREAD

**Issue by patsy-issa** [simplabs/qunit-dom#736]
This is step 1 in an effort to remove potential false positives, as it stands calling `assert.dom().exists()` and `assert.dom(find(nonExistingElement)).exists()` both default to `assert.dom(rootElement)`.

I propose that in the case of a null argument being passed in we can log a warning to the user and recommend the usage of a unique identifier to be used as `assert.dom('unique-identifier')` as the other usage may lead to a false positive.

**Comment by Turbo87** [comment]
I'm not sure about the warning. We should either throw a hard error if `undefined/null` is passed in, or make the function that looks up the element from the passed in selector handles that value correctly (which I think it does already).

**Comment by patsy-issa** [comment]
I m good with an error 👍
