### ISSUE TITLE
equivalent to .eq in jQuery?

### ISSUE THREAD

**Issue by Gaurav0** [simplabs/qunit-dom#761]
something like `assert.dom('.title').eq(1).hasText(...) // second title has text`

**Comment by Turbo87** [comment]
while I have had need for something like this in the past it's easy enough to do outside of qunit-dom and just pass in the element directly. I'd be a bit worried about this getting out of hand when we start implementing all sorts of selectors like this, so I think I'd prefer to not include this functionality in qunit-dom itself.
