### ISSUE TITLE
Assertion to count number of items on the page

### ISSUE THREAD

**Issue by patocallaghan** [simplabs/qunit-dom#81]
Currently, when you want to find a count of elements on the page you do:

``` js
assert.dom('[data-test-something]').exists({ count: 4 });
```

While this works, I find the API a bit inelegant. Any thoughts on adding a `count` alias (or something similarly named) which essentially is a wrapper around the above call?

``` js
assert.dom('[data-test-something]').count(4);
```

Feel free to close if it's not something you'd like to add.

**Comment by Turbo87** [comment]
> Feel free to close if it's not something you'd like to add

I'm not convinced... 😉

**Comment by patocallaghan** [comment]
😄 

So my thinking was we already have aliases for some other assertions like `lacksClass`, `doesNotContainText` etc, which I presume was added to increase readability, why not have a nicer alias for the `exists + count` use case.
