### ISSUE TITLE
Compatibility with `ember-qunit@5`

### ISSUE THREAD

**Issue by rwjblue** [simplabs/qunit-dom#812]
`ember-qunit@5` is (finally 😩) moving along, it brings a few major changes:

* Drop support for older Node versions
* Remove usage of APIs that are not Embroider compatible
  * `{{content-for` usage has been replaced by having the `tests/index.html` directly include our expected DOM content
  * `app.import` has been removed in favor of leveraging imports along with ember-auto-import / Embroider to process them
* Drop direct dependency on `qunit` and `@ember/test-helpers`; moving them to be `peerDependencies` (along with some helpful validations and error messages to help guide folks down the path)

The combination of these things results in a somewhat fundamental problem: tooling can no longer depend on the `QUnit` global to be defined. This is the primary issue that we need to determine how to resolve for `qunit-dom`.

Specifically, at the moment, we directly `app.import` into the `test-support.js` file:

https://github.com/simplabs/qunit-dom/blob/258f8b3a5b0d6f09364d26fec66d454bf3d471e4/index.js#L12-L22

Up until now, this has worked just fine. However, since `QUnit` itself is not directly "splatted" into the `test-support.js` file (it is within a module instead) we are no longer guaranteed that `window.QUnit` will be defined when we call `QUnit.assert.dom = ...` here:

https://github.com/simplabs/qunit-dom/blob/258f8b3a5b0d6f09364d26fec66d454bf3d471e4/lib/qunit-dom.ts#L11

**Comment by rwjblue** [comment]
My suggestion here would be do continue down the path that @ef4 started in https://github.com/simplabs/qunit-dom/pull/542:

* Remove the `app.import`s that are remaining
* Make `qunit` a peer dependency
* Update the build script to emit a `dist/qunit-dom.mjs` 
* Update `main` to point to the current `dist/qunit-dom.js` file (for "side effect" users)
* Update `modules` to point to the new `dist/qunit-dom.mjs` file
* Make this repo **not** an ember-cli addon (users would still have things work nicely by way of Embroider / ember-auto-import)

I'm working up a draft PR for y'all to take a look at (and to confirm that it generally works)...

**Comment by scalvert** [comment]
I think this makes sense to me, broadly. Who loads qunit then, and how is the ordering guaranteed? Will we no longer rely on the global `QUnit` here?

**Comment by rwjblue** [comment]
> Who loads qunit then, and how is the ordering guaranteed?

My general thought here was that we would provide a module that folks would import for side effects:

```js
// tests/test-helper.js

import 'qunit-dom';
```

> Will we no longer rely on the global QUnit here?

No, we'd update that side-effect based module to be something akin to:

```js
import * as QUnit from 'qunit';

QUnit.assert.dom = ...;
```

So we are no longer relying on the global.

**Comment by scalvert** [comment]
OK ya I assumed we were importing a module from somewhere. This seems fine, though I have to say I tend to not love side effect imports - I'd prefer an explicit invocation, but nbd.

**Comment by rwjblue** [comment]
I think we can do it either way, but requiring an import + the possible `install(QUnit)` type call just means an extra line. I don't think that's a massive problem personally though.
