### ISSUE TITLE
`Element <target> exists` error message when it does not.

### ISSUE THREAD

**Issue by adriancooney** [simplabs/qunit-dom#84]
So while using the `isNotVisible`, I tested on a selector that did not return any elements and got the following error:

```
assert.dom('.my_selector').isNotVisible();
// Throws: Element .my_selector exists
```

This message to begin with is a little cryptic because it doesn't mention visibility anywhere (which could be something we should look into). Secondly, elements matching the `.my_selector` *don't* exist! Exactly the opposite of what the error message suggests. This could be considered a bug, right? I think the offending code [lies in `findTargetElement`](https://github.com/simplabs/qunit-dom/blob/master/lib/assertions.js#L679-L700) with some interesting conditions:

```js
  findTargetElement() {
    if (this.target === null) {
      let message = `Element <unknown> exists`;
      this.pushResult({ message, result: false });
      return null;
    }

    if (typeof this.target === 'string') {
      let el = this.rootElement.querySelector(this.target);

      if (el === null) {
        let message = `Element ${this.target || '<unknown>'} exists`;
        this.pushResult({ message, result: false });
      }

      return el;

    } else if (this.target instanceof Element) {
      return this.target;

    } else {
      throw new TypeError(`Unexpected Parameter: ${this.target}`)
    }
  }
```

Am I missing something? Or any ideas on a fix? I can submit a PR if necessary.

**Comment by scalvert** [comment]
I also found a bug in the `isVisible`/`isNotVisible` assertions. The current implementation of `findTargetElement` is intertwined with `pushResult` calls. This causes issues when an element doesn't yet exist in the DOM, as  it triggers this:

```js
      if (el === null) {
        let message = `Element ${this.target || '<unknown>'} exists`;
        this.pushResult({ message, result: false });
      }
```
as @adriancooney suggests. 

There's two things here:
1. I'm not sure how the tests pass for this right now
2. I believe the `findTargetElement` function needs to be decomposed somewhat to disconnect the finding of elements from `pushResult` calls.

I'm going to take a stab at fixing this issue, as the visibility checks aren't working properly right now.

cc: @rwjblue

**Comment by scalvert** [comment]
With the above PR merged, does this address your original concern @adriancooney?

**Comment by adriancooney** [comment]
That would have cleared it up for me @scalvert, thank you!
