### ISSUE TITLE
Regression: Could not find a declaration file for module 'qunit-dom' on v1.6.0-beta.1

### ISSUE THREAD

**Issue by johanrd** [simplabs/qunit-dom#856]
1. Clone this repo: https://github.com/johanrd/qunit-dom-typescript-reproduction
2. Run `tsc`, and experience the following typescript errors:

```console
machine:qunit-dom-typescript-reproduction user$ tsc
tests/acceptance/application-test.ts:13:12 - error TS2339: Property 'dom' does not exist on type 'Assert'.

13     assert.dom('#ember-welcome-page-id-selector').exists();
              ~~~

tests/test-helper.ts:5:23 - error TS7016: Could not find a declaration file for module 'qunit-dom'. '…/qunit-dom-typescript-reproduction/node_modules/qunit-dom/index.js' implicitly has an 'any' type.
  Try `npm install @types/qunit-dom` if it exists or add a new declaration (.d.ts) file containing `declare module 'qunit-dom';`

5 import { setup } from 'qunit-dom';
``` 

`yarn add @types/qunit-dom` does not make any difference (as expected from deprecation).

Have I missed something from the migration guide and/or readme? Or is it an actual regression on `v1.6.0-beta.1`? 
thanks!

**Comment by Turbo87** [comment]
@rwjblue @scalvert could one of you have a look at ⬆️ ? 🙏

**Comment by rwjblue** [comment]
Yep. Will review, thank you for the reproduction!!

**Comment by scalvert** [comment]
Will also take a peek.

**Comment by scalvert** [comment]
Removing my local `dist` directory and rebuilding with `1.6.0-beta.1` does appear to build without a `qunit-dom.d.ts`. Looking at why.

**Comment by scalvert** [comment]
@johanrd I tested this fix in your provided reproduction and it builds fine. Thanks for the helpful repro!

**Comment by johanrd** [comment]
@scalvert Thanks for looking into this! – I ran a test now from you PR, and I actually still get the same errors:/? 

[See updated repo for reproduction](https://github.com/johanrd/qunit-dom-typescript-reproduction/commit/88ced1437bc009b13c894a096a9b5cee61e80443).

**Comment by scalvert** [comment]
Hey @johanrd,

How are you testing the changes?

**Comment by johanrd** [comment]
On https://github.com/johanrd/qunit-dom-typescript-reproduction:

```console
$ yarn remove qunit-dom
$ yarn cache clean qunit-dom
$ rm -rf node_modules
$ yarn install
$ yarn add https://github.com/simplabs/qunit-dom#e654d0e1c10fdb2b96f0255775ad66a2c0b24193 --dev
$ tsc

tests/acceptance/application-test.ts:13:12 - error TS2339: Property 'dom' does not exist on type 'Assert'.

13     assert.dom('#ember-welcome-page-id-selector').exists();
              ~~~

tests/test-helper.ts:5:23 - error TS7016: Could not find a declaration file for module 'qunit-dom'. '/Users/johanroed/rendra/qunit-dom-typescript-reproduction/node_modules/qunit-dom/index.js' implicitly has an 'any' type.
  Try `npm install @types/qunit-dom` if it exists or add a new declaration (.d.ts) file containing `declare module 'qunit-dom';`

5 import { setup } from 'qunit-dom';
                        ~~~~~~~~~~~


Found 2 errors.
```

See commit [7ae45ad](https://github.com/johanrd/qunit-dom-typescript-reproduction/commit/88ced1437bc009b13c894a096a9b5cee61e80443#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R62 ) 
FWIW: VS Code outputs the same errors as `tsc`

**Comment by scalvert** [comment]
OK, that's not going to be sufficient to test this, as `qunit-dom` is built and rolled up before it's published. Try this:

- `cd qunit-dom-typescript-reproduction`
- `yarn add https://github.com/simplabs/qunit-dom#e654d0e1c10fdb2b96f0255775ad66a2c0b24193 --dev`
- `cd node_modules/qunit-dom` (this will install `qunit-dom`'s dependencies _and_ build/rollup the package
- `cd ../.. && yarn build` (running `yarn build` is more appropriate than running `tsc` since it runs Ember's build, which in turn will compile typescript)

**Comment by johanrd** [comment]
Ah, ok, thanks – I can verify that it works after running `yarn` inside `node_modules/qunit-dom` :ok_hand:

**Comment by scalvert** [comment]
Awesome. Thanks for testing this out!
