### ISSUE TITLE
Assertions do not have a return value

### ISSUE THREAD

**Issue by lebbers** [simplabs/qunit-dom#88]
During a debug session of a failing test I was trying to see why the assertion failed (to see why the query selector was incorrect). But executing the same assertion methods in the devtools console window returned `undefined` instead of the actual result of the assertion. It would help during debugging what the result of the assertion is so that I could try the same assertion with a different selector.

So for example the current behaviour is as follows
```javascript
assert.dom('div .my-selector').exists() // Returns undefined
```
I would expect something like
```javascript
assert.dom('div .my-selector').exists() // Returns false/true
```

**Comment by Turbo87** [comment]
@lebbers does that work for any other QUnit assertion like `assert.equal()`?

**Comment by lebbers** [comment]
@Turbo87 True, but using `assert.equal()` makes it easier to inspect what the values are that are compared (the actual and expected values an still be inspected). Where in the case of `assert.dom()` the actual and expected value could not be inspected because that is something this library internally knows.

**Comment by Turbo87** [comment]
we've discussed this with a few people and this is not something that `qunit-dom` will support. `qunit-dom` will focus on running assertions that integrate with QUnit, and that API has no return values. you can however check `assert.test.assertions` to see if the previous assertions passed or failed.
