### ISSUE TITLE
Add `assert.dom(...).hasCSS({ ... })` assertion

### ISSUE THREAD

**Issue by Turbo87** [simplabs/qunit-dom#90]
### Example

```js
assert.dom('.some-element').hasCSS({
  opacity: 1,
  width: 340,
});
```

**Comment by billybonks** [comment]
i have this code :), will work on getting a pr up and running.

**Comment by brookjordan** [comment]
Maybe this should be `hasStyle`.
CSS is simply the language all browsers currently use to apply these styles.
