### ISSUE TITLE
How to do custom assertions

### ISSUE THREAD

**Issue by lindem** [simplabs/qunit-dom#97]
How would one go about adding their own, project-local assertions to qunit-dom? 

With QUnit, we can say

```javascript
QUnit.assert.myAssertion = function() {...}
```

However, to be able to do that with an object returned from QUnit.dom(...), one would have to extend a DOMAssertions object or prototype. I couldn't seem to find where that is accessible.

**Comment by Turbo87** [comment]
custom assertions like that are currently not supported

**Comment by lindem** [comment]
Are there any plans to do that in the future?

**Comment by Turbo87** [comment]
we currently have no such plans. since you can already extend `QUnit.assert` I'm not sure that we'd necessarily need a way for extending the DOM assertions too. ultimately you would have to use a lot of private API in your custom DOM assertions and since it's private we wouldn't be able to give any stability guarantees anyway.

**Comment by lindem** [comment]
Thank you for your reply.

> we currently have no such plans. 
Understood. 

> since you can already extend QUnit.assert I'm not sure that we'd necessarily need a way for extending the DOM assertions too. 
I wanted to do this because I am asserting some quality specifically about the element from `querySelector()`, which is usually `this` in your assertions. I'd imagine that I am not the only guy who wants to assert that the `div.foo` I am looking at has `data-whatever` set to a specific value while it also has `class="my-whatever", and since that is hard to read, name it `assert.dom(...).isCorrectWhatever()`; you know, project specific stuff.

Of course you can put that into `QUnit.assert`, like `assert.isCorrectWhatever(selector, message), but if you are going that far, then you can also put **all** DOM related assertions there.

**Comment by billybonks** [comment]
```
assert.dom('x').hasClass('my-whatever')
assert.dom('x').hasAttribute('data-whatever', 'value')
```

you could make a helper function
```
function assertMyTwoThings(selector){
 assert.dom('x').hasClass('my-whatever')
 assert.dom('x').hasAttribute('data-whatever', 'value')
}
```
or

or you can extend `QUnit.assert`  as @Turbo87 mention

```
QUnit.extend(QUnit.assert, {
  customDom(selector) {
    return {
       twoThingsAtOnce(){
        //this is not the real way to do the assertion but it will work
         assert.dom(selector).hasClass('my-whatever')
         assert.dom(selector).hasAttribute('data-whatever', 'value')
      }
    }
  },
});

assert.customDom('x').twoThingsAtOnce()
```
i would just write both assertions but if you really want to do it in one call i recommend the helper function.

**Comment by lindem** [comment]
Thank you for your response. The problem isn't that I don't know how to write assertions.

The problem is that there are things I would have liked to assert on the node directly in a library- or project-specific manner, and I was baffled at the response that it's just not supported and there are no plans to do so.

Even a generic thing like 

```
assert.dom(selector).satisfies(predicate, "that DOM node satisfies this predicate")
```

would have been useful. But if I am the only guy who wants extensible DOM assertions I can live with qunit-dom not supporting something like this.
